#The range in blocks that blocks will be highlighted in if not specified by the user.
default_range: 16

#The minimum range in blocks that blocks may be highlighted in.
min_range: 1

#The maximum range in blocks that blocks may be highlighted in. (for preventing server lag)
max_range: 64

#The maximum number of blocks that will be highlighted. (for preventing client lag)
max_blocks: 10000

#The color that a block type shall be highlighted in. use standard color codes.
#Only blocks that are given a color can be highlighted.
colors:
  COAL_ORE: '&8'
  IRON_ORE: '&7'
  GOLD_ORE: '&6'
  DIAMOND_ORE: '&b'
  REDSTONE_ORE: '&4'
  GLOWING_REDSTONE_ORE: '&4'
  LAPIS_ORE: '&1'
  EMERALD_ORE: '&2'
  QUARTZ_ORE: '&f'

#The block types that will be highlighted if not specified by the user.
default_blocks:
  - IRON_ORE
  - GOLD_ORE
  - DIAMOND_ORE
  - REDSTONE_ORE
  - GLOWING_REDSTONE_ORE
  - LAPIS_ORE
  - EMERALD_ORE
  - QUARTZ_ORE