name: SpelunkingTool
main: de.selebrator.orehighlighter.PluginMain
version: 0.0.1
authors: [Selebrator]
commands:
  ore:
    ussage: /ore [player]

permissions:
  ore.see.ores:
    description: see all ores
    children:
      ore.see.coal_ore: true
      ore.see.iron_ore: true
      ore.see.gold_ore: true
      ore.see.diamond_ore: true
      ore.see.redstone_ore: true
      ore.see.lapis_ore: true
      ore.see.emerald_ore: true
      ore.see.quartz_ore: true